version: '3.4'

services:
  release:
    image: tons/dc-ci:${TAG}
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/src
    environment:
      REGISTRY_USER: ${REGISTRY_USER}
      REGISTRY_PASS: ${REGISTRY_PASS}
      SERVICE: release
